// Writes extension/config.js from .env (VITE_SUPABASE_URL / VITE_SUPABASE_ANON_KEY) for local use.
import { writeFileSync } from "fs";
const { VITE_SUPABASE_URL: url, VITE_SUPABASE_ANON_KEY: key } = process.env;
if (!url || !key) throw new Error("Set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in .env first");
const apiBase = process.env.EXT_API_BASE || "http://localhost:3001";
const appUrl = process.env.EXT_APP_URL || "http://localhost:5173/app";
writeFileSync(
  new URL("../extension/config.js", import.meta.url),
  `// Generated by npm run ext:config – do not commit.\nexport const CONFIG = ${JSON.stringify({ apiBase, appUrl, supabaseUrl: url, supabaseAnonKey: key }, null, 2)};\n`,
);
console.log("extension/config.js written for", apiBase);
